services:
    # nginx
    web:
        build:
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        restart: unless-stopped #In Prod, this should be "always"
        environment:
            #In prod, this should be fx a .env file
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: docker-php
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
    # redis

volumes:
    mysqldata: