services:
    # nginx
    web:
        image: nginx:1.22
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: app_dev
        volumes:
            - ./app:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway

    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: docker-php
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
    # redis
    cache:
        image: redis:6.2.6
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    mysqldata: